# Generated by Django 2.0.1 on 2018-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20180124_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science And Engineering'), ('IT', 'Information Technology'), ('EC', 'Electronics Engineering'), ('EEE', 'Electrical And Electronics Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('IC', 'Instrumentation and Control')], help_text='Enter your branch initials i.e.. EEE for electrical and electronics engineering', max_length=10),
        ),
    ]
